{'class': [{'keyword': 'class'},
           {'identifier': 'Bat'},
           {'symbol': '{'},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'x'},
                            {'symbol': ','},
                            {'identifier': 'y'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'width'},
                            {'symbol': ','},
                            {'identifier': 'height'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'direction'},
                            {'symbol': ';'}]},
           {'subroutineDec': [{'keyword': 'constructor'},
                              {'identifier': 'Bat'},
                              {'identifier': 'new'},
                              {'symbol': '('},
                              {'parameterList': [{'keyword': 'int'},
                                                 {'identifier': 'Ax'},
                                                 {'symbol': ','},
                                                 {'keyword': 'int'},
                                                 {'identifier': 'Ay'},
                                                 {'symbol': ','},
                                                 {'keyword': 'int'},
                                                 {'identifier': 'Awidth'},
                                                 {'symbol': ','},
                                                 {'keyword': 'int'},
                                                 {'identifier': 'Aheight'}]},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'x'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Ax'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'y'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Ay'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'width'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Awidth'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'height'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Aheight'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'direction'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'integerConstant': '2'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'show'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'expression': [{'term': [{'keyword': 'this'}]}]},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'dispose'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Memory'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'deAlloc'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'keyword': 'this'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'show'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'setColor'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'keyword': 'true'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'draw'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'hide'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'setColor'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'keyword': 'false'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'draw'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'draw'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'drawRectangle'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'identifier': 'x'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'identifier': 'y'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                           {'symbol': '+'},
                                                                                                                                           {'term': [{'identifier': 'width'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'identifier': 'y'}]},
                                                                                                                                           {'symbol': '+'},
                                                                                                                                           {'term': [{'identifier': 'height'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'setDirection'},
                              {'symbol': '('},
                              {'parameterList': [{'keyword': 'int'},
                                                 {'identifier': 'Adirection'}]},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'direction'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Adirection'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'int'},
                              {'identifier': 'getLeft'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'returnStatement': [{'keyword': 'return'},
                                                                                       {'expression': [{'term': [{'identifier': 'x'}]}]},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'int'},
                              {'identifier': 'getRight'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'returnStatement': [{'keyword': 'return'},
                                                                                       {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                       {'symbol': '+'},
                                                                                                       {'term': [{'identifier': 'width'}]}]},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'setWidth'},
                              {'symbol': '('},
                              {'parameterList': [{'keyword': 'int'},
                                                 {'identifier': 'Awidth'}]},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'hide'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'width'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'identifier': 'Awidth'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'show'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'move'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'ifStatement': [{'keyword': 'if'},
                                                                                   {'symbol': '('},
                                                                                   {'expression': [{'term': [{'identifier': 'direction'}]},
                                                                                                   {'symbol': '='},
                                                                                                   {'term': [{'integerConstant': '1'}]}]},
                                                                                   {'symbol': ')'},
                                                                                   {'symbol': '{'},
                                                                                   {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'x'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                     {'symbol': '-'},
                                                                                                                                     {'term': [{'integerConstant': '4'}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'ifStatement': [{'keyword': 'if'},
                                                                                                                    {'symbol': '('},
                                                                                                                    {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                    {'symbol': '<'},
                                                                                                                                    {'term': [{'integerConstant': '0'}]}]},
                                                                                                                    {'symbol': ')'},
                                                                                                                    {'symbol': '{'},
                                                                                                                    {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                      {'identifier': 'x'},
                                                                                                                                                      {'symbol': '='},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                                                                                      {'symbol': ';'}]}]},
                                                                                                                    {'symbol': '}'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'setColor'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'keyword': 'false'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'drawRectangle'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'symbol': '('},
                                                                                                                                                                                      {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                                                      {'symbol': '+'},
                                                                                                                                                                                                      {'term': [{'identifier': 'width'}]}]},
                                                                                                                                                                                      {'symbol': ')'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'integerConstant': '1'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'symbol': '('},
                                                                                                                                                                                      {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                                                      {'symbol': '+'},
                                                                                                                                                                                                      {'term': [{'identifier': 'width'}]}]},
                                                                                                                                                                                      {'symbol': ')'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'integerConstant': '4'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'identifier': 'height'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'setColor'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'keyword': 'true'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'drawRectangle'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'identifier': 'x'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'integerConstant': '3'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'identifier': 'height'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]}]},
                                                                                   {'symbol': '}'},
                                                                                   {'keyword': 'else'},
                                                                                   {'symbol': '{'},
                                                                                   {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'x'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                     {'symbol': '+'},
                                                                                                                                     {'term': [{'integerConstant': '4'}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'ifStatement': [{'keyword': 'if'},
                                                                                                                    {'symbol': '('},
                                                                                                                    {'expression': [{'term': [{'symbol': '('},
                                                                                                                                              {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                              {'symbol': '+'},
                                                                                                                                                              {'term': [{'identifier': 'width'}]}]},
                                                                                                                                              {'symbol': ')'}]},
                                                                                                                                    {'symbol': '>'},
                                                                                                                                    {'term': [{'integerConstant': '511'}]}]},
                                                                                                                    {'symbol': ')'},
                                                                                                                    {'symbol': '{'},
                                                                                                                    {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                      {'identifier': 'x'},
                                                                                                                                                      {'symbol': '='},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '511'}]},
                                                                                                                                                                      {'symbol': '-'},
                                                                                                                                                                      {'term': [{'identifier': 'width'}]}]},
                                                                                                                                                      {'symbol': ';'}]}]},
                                                                                                                    {'symbol': '}'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'setColor'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'keyword': 'false'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'drawRectangle'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                            {'symbol': '-'},
                                                                                                                                                                            {'term': [{'integerConstant': '4'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                            {'symbol': '-'},
                                                                                                                                                                            {'term': [{'integerConstant': '1'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'identifier': 'height'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'setColor'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'keyword': 'true'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'drawRectangle'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'symbol': '('},
                                                                                                                                                                                      {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                                                      {'symbol': '+'},
                                                                                                                                                                                                      {'term': [{'identifier': 'width'}]}]},
                                                                                                                                                                                      {'symbol': ')'}]},
                                                                                                                                                                            {'symbol': '-'},
                                                                                                                                                                            {'term': [{'integerConstant': '3'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'x'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'identifier': 'width'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'identifier': 'y'}]},
                                                                                                                                                                            {'symbol': '+'},
                                                                                                                                                                            {'term': [{'identifier': 'height'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]}]},
                                                                                   {'symbol': '}'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'symbol': '}'}]}