{'class': [{'keyword': 'class'},
           {'identifier': 'Main'},
           {'symbol': '{'},
           {'subroutineDec': [{'keyword': 'function'},
                              {'keyword': 'void'},
                              {'identifier': 'main'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'varDec': [{'keyword': 'var'},
                                                              {'identifier': 'PongGame'},
                                                              {'identifier': 'game'},
                                                              {'symbol': ';'}]},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'PongGame'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'newInstance'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'game'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'subroutineCall': [{'identifier': 'PongGame'},
                                                                                                                                  {'symbol': '.'},
                                                                                                                                  {'identifier': 'getInstance'},
                                                                                                                                  {'symbol': '('},
                                                                                                                                  {'expressionList': []},
                                                                                                                                  {'symbol': ')'}]}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'game'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'run'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'game'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'dispose'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'symbol': '}'}]}