{'class': [{'keyword': 'class'},
           {'identifier': 'PongGame'},
           {'symbol': '{'},
           {'classVarDec': [{'keyword': 'static'},
                            {'identifier': 'PongGame'},
                            {'identifier': 'instance'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'identifier': 'Bat'},
                            {'identifier': 'bat'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'identifier': 'Ball'},
                            {'identifier': 'ball'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'wall'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'boolean'},
                            {'identifier': 'exit'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'score'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'lastWall'},
                            {'symbol': ';'}]},
           {'classVarDec': [{'keyword': 'field'},
                            {'keyword': 'int'},
                            {'identifier': 'batWidth'},
                            {'symbol': ';'}]},
           {'subroutineDec': [{'keyword': 'constructor'},
                              {'identifier': 'PongGame'},
                              {'identifier': 'new'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'clearScreen'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'batWidth'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'integerConstant': '50'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'bat'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'subroutineCall': [{'identifier': 'Bat'},
                                                                                                                                  {'symbol': '.'},
                                                                                                                                  {'identifier': 'new'},
                                                                                                                                  {'symbol': '('},
                                                                                                                                  {'expressionList': [{'expression': [{'term': [{'integerConstant': '230'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '229'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'identifier': 'batWidth'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '7'}]}]}]},
                                                                                                                                  {'symbol': ')'}]}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'ball'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'subroutineCall': [{'identifier': 'Ball'},
                                                                                                                                  {'symbol': '.'},
                                                                                                                                  {'identifier': 'new'},
                                                                                                                                  {'symbol': '('},
                                                                                                                                  {'expressionList': [{'expression': [{'term': [{'integerConstant': '253'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '222'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '511'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                                                                                      {'symbol': ','},
                                                                                                                                                      {'expression': [{'term': [{'integerConstant': '229'}]}]}]},
                                                                                                                                  {'symbol': ')'}]}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'ball'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'setDestination'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'integerConstant': '400'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'integerConstant': '0'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Screen'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'drawRectangle'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'integerConstant': '238'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'integerConstant': '511'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'integerConstant': '240'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Output'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'moveCursor'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'integerConstant': '22'}]}]},
                                                                                                                           {'symbol': ','},
                                                                                                                           {'expression': [{'term': [{'integerConstant': '0'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Output'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'printString'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'stringConstant': '"Score: '
                                                                                                                                                                        '0"'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'exit'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'keyword': 'false'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'score'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'wall'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'lastWall'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'expression': [{'term': [{'keyword': 'this'}]}]},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'dispose'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'bat'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'dispose'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'ball'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'dispose'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': []},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'doStatement': [{'keyword': 'do'},
                                                                                   {'subroutineCall': [{'identifier': 'Memory'},
                                                                                                       {'symbol': '.'},
                                                                                                       {'identifier': 'deAlloc'},
                                                                                                       {'symbol': '('},
                                                                                                       {'expressionList': [{'expression': [{'term': [{'keyword': 'this'}]}]}]},
                                                                                                       {'symbol': ')'}]},
                                                                                   {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'function'},
                              {'keyword': 'void'},
                              {'identifier': 'newInstance'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'instance'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'subroutineCall': [{'identifier': 'PongGame'},
                                                                                                                                  {'symbol': '.'},
                                                                                                                                  {'identifier': 'new'},
                                                                                                                                  {'symbol': '('},
                                                                                                                                  {'expressionList': []},
                                                                                                                                  {'symbol': ')'}]}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'function'},
                              {'identifier': 'PongGame'},
                              {'identifier': 'getInstance'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'statements': [{'returnStatement': [{'keyword': 'return'},
                                                                                       {'expression': [{'term': [{'identifier': 'instance'}]}]},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'run'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'varDec': [{'keyword': 'var'},
                                                              {'keyword': 'char'},
                                                              {'identifier': 'key'},
                                                              {'symbol': ';'}]},
                                                  {'statements': [{'whileStatement': [{'keyword': 'while'},
                                                                                      {'symbol': '('},
                                                                                      {'expression': [{'term': [{'symbol': '~'},
                                                                                                                {'term': [{'identifier': 'exit'}]}]}]},
                                                                                      {'symbol': ')'},
                                                                                      {'symbol': '{'},
                                                                                      {'statements': [{'whileStatement': [{'keyword': 'while'},
                                                                                                                          {'symbol': '('},
                                                                                                                          {'expression': [{'term': [{'symbol': '('},
                                                                                                                                                    {'expression': [{'term': [{'identifier': 'key'}]},
                                                                                                                                                                    {'symbol': '='},
                                                                                                                                                                    {'term': [{'integerConstant': '0'}]}]},
                                                                                                                                                    {'symbol': ')'}]},
                                                                                                                                          {'symbol': '&'},
                                                                                                                                          {'term': [{'symbol': '('},
                                                                                                                                                    {'expression': [{'term': [{'symbol': '~'},
                                                                                                                                                                              {'term': [{'identifier': 'exit'}]}]}]},
                                                                                                                                                    {'symbol': ')'}]}]},
                                                                                                                          {'symbol': ')'},
                                                                                                                          {'symbol': '{'},
                                                                                                                          {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                            {'identifier': 'key'},
                                                                                                                                                            {'symbol': '='},
                                                                                                                                                            {'expression': [{'term': [{'subroutineCall': [{'identifier': 'Keyboard'},
                                                                                                                                                                                                          {'symbol': '.'},
                                                                                                                                                                                                          {'identifier': 'keyPressed'},
                                                                                                                                                                                                          {'symbol': '('},
                                                                                                                                                                                                          {'expressionList': []},
                                                                                                                                                                                                          {'symbol': ')'}]}]}]},
                                                                                                                                                            {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                               {'symbol': '.'},
                                                                                                                                                                               {'identifier': 'move'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': []},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'moveBall'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': []},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'Sys'},
                                                                                                                                                                               {'symbol': '.'},
                                                                                                                                                                               {'identifier': 'wait'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': [{'expression': [{'term': [{'integerConstant': '50'}]}]}]},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]}]},
                                                                                                                          {'symbol': '}'}]},
                                                                                                      {'ifStatement': [{'keyword': 'if'},
                                                                                                                       {'symbol': '('},
                                                                                                                       {'expression': [{'term': [{'identifier': 'key'}]},
                                                                                                                                       {'symbol': '='},
                                                                                                                                       {'term': [{'integerConstant': '130'}]}]},
                                                                                                                       {'symbol': ')'},
                                                                                                                       {'symbol': '{'},
                                                                                                                       {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                                                                                        {'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                            {'symbol': '.'},
                                                                                                                                                                            {'identifier': 'setDirection'},
                                                                                                                                                                            {'symbol': '('},
                                                                                                                                                                            {'expressionList': [{'expression': [{'term': [{'integerConstant': '1'}]}]}]},
                                                                                                                                                                            {'symbol': ')'}]},
                                                                                                                                                        {'symbol': ';'}]}]},
                                                                                                                       {'symbol': '}'},
                                                                                                                       {'keyword': 'else'},
                                                                                                                       {'symbol': '{'},
                                                                                                                       {'statements': [{'ifStatement': [{'keyword': 'if'},
                                                                                                                                                        {'symbol': '('},
                                                                                                                                                        {'expression': [{'term': [{'identifier': 'key'}]},
                                                                                                                                                                        {'symbol': '='},
                                                                                                                                                                        {'term': [{'integerConstant': '132'}]}]},
                                                                                                                                                        {'symbol': ')'},
                                                                                                                                                        {'symbol': '{'},
                                                                                                                                                        {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                                                                                                                         {'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                                                             {'symbol': '.'},
                                                                                                                                                                                                             {'identifier': 'setDirection'},
                                                                                                                                                                                                             {'symbol': '('},
                                                                                                                                                                                                             {'expressionList': [{'expression': [{'term': [{'integerConstant': '2'}]}]}]},
                                                                                                                                                                                                             {'symbol': ')'}]},
                                                                                                                                                                                         {'symbol': ';'}]}]},
                                                                                                                                                        {'symbol': '}'},
                                                                                                                                                        {'keyword': 'else'},
                                                                                                                                                        {'symbol': '{'},
                                                                                                                                                        {'statements': [{'ifStatement': [{'keyword': 'if'},
                                                                                                                                                                                         {'symbol': '('},
                                                                                                                                                                                         {'expression': [{'term': [{'identifier': 'key'}]},
                                                                                                                                                                                                         {'symbol': '='},
                                                                                                                                                                                                         {'term': [{'integerConstant': '140'}]}]},
                                                                                                                                                                                         {'symbol': ')'},
                                                                                                                                                                                         {'symbol': '{'},
                                                                                                                                                                                         {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                                                                                           {'identifier': 'exit'},
                                                                                                                                                                                                                           {'symbol': '='},
                                                                                                                                                                                                                           {'expression': [{'term': [{'keyword': 'true'}]}]},
                                                                                                                                                                                                                           {'symbol': ';'}]}]},
                                                                                                                                                                                         {'symbol': '}'}]}]},
                                                                                                                                                        {'symbol': '}'}]}]},
                                                                                                                       {'symbol': '}'}]},
                                                                                                      {'whileStatement': [{'keyword': 'while'},
                                                                                                                          {'symbol': '('},
                                                                                                                          {'expression': [{'term': [{'symbol': '('},
                                                                                                                                                    {'expression': [{'term': [{'symbol': '~'},
                                                                                                                                                                              {'term': [{'symbol': '('},
                                                                                                                                                                                        {'expression': [{'term': [{'identifier': 'key'}]},
                                                                                                                                                                                                        {'symbol': '='},
                                                                                                                                                                                                        {'term': [{'integerConstant': '0'}]}]},
                                                                                                                                                                                        {'symbol': ')'}]}]}]},
                                                                                                                                                    {'symbol': ')'}]},
                                                                                                                                          {'symbol': '&'},
                                                                                                                                          {'term': [{'symbol': '('},
                                                                                                                                                    {'expression': [{'term': [{'symbol': '~'},
                                                                                                                                                                              {'term': [{'identifier': 'exit'}]}]}]},
                                                                                                                                                    {'symbol': ')'}]}]},
                                                                                                                          {'symbol': ')'},
                                                                                                                          {'symbol': '{'},
                                                                                                                          {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                            {'identifier': 'key'},
                                                                                                                                                            {'symbol': '='},
                                                                                                                                                            {'expression': [{'term': [{'subroutineCall': [{'identifier': 'Keyboard'},
                                                                                                                                                                                                          {'symbol': '.'},
                                                                                                                                                                                                          {'identifier': 'keyPressed'},
                                                                                                                                                                                                          {'symbol': '('},
                                                                                                                                                                                                          {'expressionList': []},
                                                                                                                                                                                                          {'symbol': ')'}]}]}]},
                                                                                                                                                            {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                               {'symbol': '.'},
                                                                                                                                                                               {'identifier': 'move'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': []},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'moveBall'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': []},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]},
                                                                                                                                          {'doStatement': [{'keyword': 'do'},
                                                                                                                                                           {'subroutineCall': [{'identifier': 'Sys'},
                                                                                                                                                                               {'symbol': '.'},
                                                                                                                                                                               {'identifier': 'wait'},
                                                                                                                                                                               {'symbol': '('},
                                                                                                                                                                               {'expressionList': [{'expression': [{'term': [{'integerConstant': '50'}]}]}]},
                                                                                                                                                                               {'symbol': ')'}]},
                                                                                                                                                           {'symbol': ';'}]}]},
                                                                                                                          {'symbol': '}'}]}]},
                                                                                      {'symbol': '}'}]},
                                                                  {'ifStatement': [{'keyword': 'if'},
                                                                                   {'symbol': '('},
                                                                                   {'expression': [{'term': [{'identifier': 'exit'}]}]},
                                                                                   {'symbol': ')'},
                                                                                   {'symbol': '{'},
                                                                                   {'statements': [{'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Output'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'moveCursor'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'integerConstant': '10'}]}]},
                                                                                                                                                            {'symbol': ','},
                                                                                                                                                            {'expression': [{'term': [{'integerConstant': '27'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'Output'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'printString'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'stringConstant': '"Game '
                                                                                                                                                                                                         'Over"'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]}]},
                                                                                   {'symbol': '}'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'subroutineDec': [{'keyword': 'method'},
                              {'keyword': 'void'},
                              {'identifier': 'moveBall'},
                              {'symbol': '('},
                              {'parameterList': []},
                              {'symbol': ')'},
                              {'subroutineBody': [{'symbol': '{'},
                                                  {'varDec': [{'keyword': 'var'},
                                                              {'keyword': 'int'},
                                                              {'identifier': 'bouncingDirection'},
                                                              {'symbol': ','},
                                                              {'identifier': 'batLeft'},
                                                              {'symbol': ','},
                                                              {'identifier': 'batRight'},
                                                              {'symbol': ','},
                                                              {'identifier': 'ballLeft'},
                                                              {'symbol': ','},
                                                              {'identifier': 'ballRight'},
                                                              {'symbol': ';'}]},
                                                  {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                    {'identifier': 'wall'},
                                                                                    {'symbol': '='},
                                                                                    {'expression': [{'term': [{'subroutineCall': [{'identifier': 'ball'},
                                                                                                                                  {'symbol': '.'},
                                                                                                                                  {'identifier': 'move'},
                                                                                                                                  {'symbol': '('},
                                                                                                                                  {'expressionList': []},
                                                                                                                                  {'symbol': ')'}]}]}]},
                                                                                    {'symbol': ';'}]},
                                                                  {'ifStatement': [{'keyword': 'if'},
                                                                                   {'symbol': '('},
                                                                                   {'expression': [{'term': [{'symbol': '('},
                                                                                                             {'expression': [{'term': [{'identifier': 'wall'}]},
                                                                                                                             {'symbol': '>'},
                                                                                                                             {'term': [{'integerConstant': '0'}]}]},
                                                                                                             {'symbol': ')'}]},
                                                                                                   {'symbol': '&'},
                                                                                                   {'term': [{'symbol': '('},
                                                                                                             {'expression': [{'term': [{'symbol': '~'},
                                                                                                                                       {'term': [{'symbol': '('},
                                                                                                                                                 {'expression': [{'term': [{'identifier': 'wall'}]},
                                                                                                                                                                 {'symbol': '='},
                                                                                                                                                                 {'term': [{'identifier': 'lastWall'}]}]},
                                                                                                                                                 {'symbol': ')'}]}]}]},
                                                                                                             {'symbol': ')'}]}]},
                                                                                   {'symbol': ')'},
                                                                                   {'symbol': '{'},
                                                                                   {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'lastWall'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'identifier': 'wall'}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'bouncingDirection'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'integerConstant': '0'}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'batLeft'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                   {'symbol': '.'},
                                                                                                                                                                   {'identifier': 'getLeft'},
                                                                                                                                                                   {'symbol': '('},
                                                                                                                                                                   {'expressionList': []},
                                                                                                                                                                   {'symbol': ')'}]}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'batRight'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                   {'symbol': '.'},
                                                                                                                                                                   {'identifier': 'getRight'},
                                                                                                                                                                   {'symbol': '('},
                                                                                                                                                                   {'expressionList': []},
                                                                                                                                                                   {'symbol': ')'}]}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'ballLeft'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'subroutineCall': [{'identifier': 'ball'},
                                                                                                                                                                   {'symbol': '.'},
                                                                                                                                                                   {'identifier': 'getLeft'},
                                                                                                                                                                   {'symbol': '('},
                                                                                                                                                                   {'expressionList': []},
                                                                                                                                                                   {'symbol': ')'}]}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'letStatement': [{'keyword': 'let'},
                                                                                                                     {'identifier': 'ballRight'},
                                                                                                                     {'symbol': '='},
                                                                                                                     {'expression': [{'term': [{'subroutineCall': [{'identifier': 'ball'},
                                                                                                                                                                   {'symbol': '.'},
                                                                                                                                                                   {'identifier': 'getRight'},
                                                                                                                                                                   {'symbol': '('},
                                                                                                                                                                   {'expressionList': []},
                                                                                                                                                                   {'symbol': ')'}]}]}]},
                                                                                                                     {'symbol': ';'}]},
                                                                                                   {'ifStatement': [{'keyword': 'if'},
                                                                                                                    {'symbol': '('},
                                                                                                                    {'expression': [{'term': [{'identifier': 'wall'}]},
                                                                                                                                    {'symbol': '='},
                                                                                                                                    {'term': [{'integerConstant': '4'}]}]},
                                                                                                                    {'symbol': ')'},
                                                                                                                    {'symbol': '{'},
                                                                                                                    {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                      {'identifier': 'exit'},
                                                                                                                                                      {'symbol': '='},
                                                                                                                                                      {'expression': [{'term': [{'symbol': '('},
                                                                                                                                                                                {'expression': [{'term': [{'identifier': 'batLeft'}]},
                                                                                                                                                                                                {'symbol': '>'},
                                                                                                                                                                                                {'term': [{'identifier': 'ballRight'}]}]},
                                                                                                                                                                                {'symbol': ')'}]},
                                                                                                                                                                      {'symbol': '|'},
                                                                                                                                                                      {'term': [{'symbol': '('},
                                                                                                                                                                                {'expression': [{'term': [{'identifier': 'batRight'}]},
                                                                                                                                                                                                {'symbol': '<'},
                                                                                                                                                                                                {'term': [{'identifier': 'ballLeft'}]}]},
                                                                                                                                                                                {'symbol': ')'}]}]},
                                                                                                                                                      {'symbol': ';'}]},
                                                                                                                                    {'ifStatement': [{'keyword': 'if'},
                                                                                                                                                     {'symbol': '('},
                                                                                                                                                     {'expression': [{'term': [{'symbol': '~'},
                                                                                                                                                                               {'term': [{'identifier': 'exit'}]}]}]},
                                                                                                                                                     {'symbol': ')'},
                                                                                                                                                     {'symbol': '{'},
                                                                                                                                                     {'statements': [{'ifStatement': [{'keyword': 'if'},
                                                                                                                                                                                      {'symbol': '('},
                                                                                                                                                                                      {'expression': [{'term': [{'identifier': 'ballRight'}]},
                                                                                                                                                                                                      {'symbol': '<'},
                                                                                                                                                                                                      {'term': [{'symbol': '('},
                                                                                                                                                                                                                {'expression': [{'term': [{'identifier': 'batLeft'}]},
                                                                                                                                                                                                                                {'symbol': '+'},
                                                                                                                                                                                                                                {'term': [{'integerConstant': '10'}]}]},
                                                                                                                                                                                                                {'symbol': ')'}]}]},
                                                                                                                                                                                      {'symbol': ')'},
                                                                                                                                                                                      {'symbol': '{'},
                                                                                                                                                                                      {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                                                                                        {'identifier': 'bouncingDirection'},
                                                                                                                                                                                                                        {'symbol': '='},
                                                                                                                                                                                                                        {'expression': [{'term': [{'symbol': '-'},
                                                                                                                                                                                                                                                  {'term': [{'integerConstant': '1'}]}]}]},
                                                                                                                                                                                                                        {'symbol': ';'}]}]},
                                                                                                                                                                                      {'symbol': '}'},
                                                                                                                                                                                      {'keyword': 'else'},
                                                                                                                                                                                      {'symbol': '{'},
                                                                                                                                                                                      {'statements': [{'ifStatement': [{'keyword': 'if'},
                                                                                                                                                                                                                       {'symbol': '('},
                                                                                                                                                                                                                       {'expression': [{'term': [{'identifier': 'ballLeft'}]},
                                                                                                                                                                                                                                       {'symbol': '>'},
                                                                                                                                                                                                                                       {'term': [{'symbol': '('},
                                                                                                                                                                                                                                                 {'expression': [{'term': [{'identifier': 'batRight'}]},
                                                                                                                                                                                                                                                                 {'symbol': '-'},
                                                                                                                                                                                                                                                                 {'term': [{'integerConstant': '10'}]}]},
                                                                                                                                                                                                                                                 {'symbol': ')'}]}]},
                                                                                                                                                                                                                       {'symbol': ')'},
                                                                                                                                                                                                                       {'symbol': '{'},
                                                                                                                                                                                                                       {'statements': [{'letStatement': [{'keyword': 'let'},
                                                                                                                                                                                                                                                         {'identifier': 'bouncingDirection'},
                                                                                                                                                                                                                                                         {'symbol': '='},
                                                                                                                                                                                                                                                         {'expression': [{'term': [{'integerConstant': '1'}]}]},
                                                                                                                                                                                                                                                         {'symbol': ';'}]}]},
                                                                                                                                                                                                                       {'symbol': '}'}]}]},
                                                                                                                                                                                      {'symbol': '}'}]},
                                                                                                                                                                     {'letStatement': [{'keyword': 'let'},
                                                                                                                                                                                       {'identifier': 'batWidth'},
                                                                                                                                                                                       {'symbol': '='},
                                                                                                                                                                                       {'expression': [{'term': [{'identifier': 'batWidth'}]},
                                                                                                                                                                                                       {'symbol': '-'},
                                                                                                                                                                                                       {'term': [{'integerConstant': '2'}]}]},
                                                                                                                                                                                       {'symbol': ';'}]},
                                                                                                                                                                     {'doStatement': [{'keyword': 'do'},
                                                                                                                                                                                      {'subroutineCall': [{'identifier': 'bat'},
                                                                                                                                                                                                          {'symbol': '.'},
                                                                                                                                                                                                          {'identifier': 'setWidth'},
                                                                                                                                                                                                          {'symbol': '('},
                                                                                                                                                                                                          {'expressionList': [{'expression': [{'term': [{'identifier': 'batWidth'}]}]}]},
                                                                                                                                                                                                          {'symbol': ')'}]},
                                                                                                                                                                                      {'symbol': ';'}]},
                                                                                                                                                                     {'letStatement': [{'keyword': 'let'},
                                                                                                                                                                                       {'identifier': 'score'},
                                                                                                                                                                                       {'symbol': '='},
                                                                                                                                                                                       {'expression': [{'term': [{'identifier': 'score'}]},
                                                                                                                                                                                                       {'symbol': '+'},
                                                                                                                                                                                                       {'term': [{'integerConstant': '1'}]}]},
                                                                                                                                                                                       {'symbol': ';'}]},
                                                                                                                                                                     {'doStatement': [{'keyword': 'do'},
                                                                                                                                                                                      {'subroutineCall': [{'identifier': 'Output'},
                                                                                                                                                                                                          {'symbol': '.'},
                                                                                                                                                                                                          {'identifier': 'moveCursor'},
                                                                                                                                                                                                          {'symbol': '('},
                                                                                                                                                                                                          {'expressionList': [{'expression': [{'term': [{'integerConstant': '22'}]}]},
                                                                                                                                                                                                                              {'symbol': ','},
                                                                                                                                                                                                                              {'expression': [{'term': [{'integerConstant': '7'}]}]}]},
                                                                                                                                                                                                          {'symbol': ')'}]},
                                                                                                                                                                                      {'symbol': ';'}]},
                                                                                                                                                                     {'doStatement': [{'keyword': 'do'},
                                                                                                                                                                                      {'subroutineCall': [{'identifier': 'Output'},
                                                                                                                                                                                                          {'symbol': '.'},
                                                                                                                                                                                                          {'identifier': 'printInt'},
                                                                                                                                                                                                          {'symbol': '('},
                                                                                                                                                                                                          {'expressionList': [{'expression': [{'term': [{'identifier': 'score'}]}]}]},
                                                                                                                                                                                                          {'symbol': ')'}]},
                                                                                                                                                                                      {'symbol': ';'}]}]},
                                                                                                                                                     {'symbol': '}'}]}]},
                                                                                                                    {'symbol': '}'}]},
                                                                                                   {'doStatement': [{'keyword': 'do'},
                                                                                                                    {'subroutineCall': [{'identifier': 'ball'},
                                                                                                                                        {'symbol': '.'},
                                                                                                                                        {'identifier': 'bounce'},
                                                                                                                                        {'symbol': '('},
                                                                                                                                        {'expressionList': [{'expression': [{'term': [{'identifier': 'bouncingDirection'}]}]}]},
                                                                                                                                        {'symbol': ')'}]},
                                                                                                                    {'symbol': ';'}]}]},
                                                                                   {'symbol': '}'}]},
                                                                  {'returnStatement': [{'keyword': 'return'},
                                                                                       {'symbol': ';'}]}]},
                                                  {'symbol': '}'}]}]},
           {'symbol': '}'}]}